{% set name = "skua" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=69
    - wheel
  run:
    - python >=3.10
    - pysam >=0.22

test:
  imports:
    - skua
  commands:
    - skua annotate --help

about:
  home: https://github.com/micknudsen/skua
  summary: Predatory and kleptoparasitic variant caller for detecting subclonal mutations in deep sequencing data
  license: MIT
  license_file: LICENSE
